export interface Datum {
  AlbumArt?: string;
  ArtistArt?: string;
  ArtistGender?: number;
  CoverArtFallback_Artist?: string;
  FeaturedDesc?: string;
  PlaylistCount?: string;
  album?: string;
  albumID?: string;
  albumexclusive?: number;
  allowoffline?: number;
  arabictext?: number;
  artist?: string;
  artistID?: string;
  bitrate?: number;
  bitrates?: string;
  cachedtime?: Date;
  cleardetails?: number;
  count?: string;
  coverArt?: string;
  coverArtID?: string;
  coverArtImage?: string;
  coverArtSize?: number;
  coverartid?: string;
  deeplink?: string;
  details?: string;
  duration?: string;
  explicit?: string;
  followers?: number;
  genre?: string;
  hasKaraoke?: boolean;
  hasvideo?: string;
  hexcolor?: string;
  id?: number | string;
  index?: number;
  isAutoMixable?: boolean;
  is_original?: number;
  iscoverwithtext?: string;
  iscustomcover?: boolean;
  keywords?: string[];
  languageid?: number | string;
  likes?: number;
  locked_content_partner_ids?: any[];
  lyrics?: number;
  lyricsupdatedon?: Date | null;
  name?: string;
  nameAr?: string;
  nofollow?: boolean;
  nouservideo?: string;
  numfollowers?: number;
  rankchange?: string;
  releasedate?: Date;
  seec?: string;
  selected?: string;
  single?: string;
  size?: string;
  songorder?: null;
  subtitles?: any[];
  thumbnailid?: string;
  title?: string;
  track?: number | string;
  verified?: number;
  vibes?: number[];
  videoduration?: string;
  videoid?: string;
  videoreleasedate?: Date;
  year?: string;
}
