import type { Button } from "./Button";
import type { Section } from "./Section";
import type { WebMetas } from "./WebMetas";

export interface SongResponse {
  angtime: number;
  status: string;
  version: string;
  webplayer: number;
  web_metas: WebMetas;
  screenshot_share_enabled: number;
  screenshot_share_prepend: string;
  responsetype: string;
  list_type: string;
  nofollow: boolean;
  id: string;
  title: string;
  album: string;
  albumID: string;
  artist: string;
  artistID: string;
  track: number;
  year: string;
  duration: string;
  coverArt: string;
  ArtistArt: string;
  ArtistGender: number;
  allowoffline: number;
  genre: string;
  AlbumArt: string;
  keywords: string[];
  languageid: number;
  bitrates: string;
  hexcolor: string;
  nouservideo: string;
  cleardetails: number;
  bitrate: number;
  size: string;
  releasedate: Date;
  arabictext: number;
  explicit: string;
  single: string;
  lyrics: number;
  lyricsupdatedon: Date;
  subtitles: any[];
  is_original: number;
  vibes: any[];
  locked_content_partner_ids: any[];
  hasKaraoke: boolean;
  isAutoMixable: boolean;
  description: null;
  likes: number;
  plays: number;
  buttons: Button[];
  sections: Section[];
}
